### PR TITLE
Making shape-key export work with modifiers like mirror.

### PR DESCRIPTION
**Pull request by xenodora**
Modified the morph/shape-key conversion so it can handle modifiers that change the vertex count (e.g. mirror).

### CODE REVIEW

**Comment by reattiva** [comment]
Thank you.

**Comment by Modanung** [comment]
I'm experiencing trouble with the exporter _after_ this commit.
I some cases models are exported without errors or warnings, yet they crash the Urho3D application. It seems to happen in cases where modifiers are either present or have been applied.

**Comment by Modanung** [comment]
Maybe there were some conflicting files. After reactivating the latest version everything seems fine. :)

**Comment by reattiva** [comment]
Glad you've solved, the "without shape keys" was infact suspicious.

**Pull request merged**
